"""init

Revision ID: 9450c25fb74c
Revises: 
Create Date: 2025-09-11 14:58:12.996750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9450c25fb74c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('reading_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('books_read', sa.Integer(), nullable=False),
    sa.Column('pages_read', sa.Integer(), nullable=False),
    sa.Column('words_read', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reading_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('full_pages', sa.Integer(), nullable=False),
    sa.Column('full_words', sa.Integer(), nullable=False),
    sa.Column('pages_read', sa.Integer(), nullable=False),
    sa.Column('words_read', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['reading_logs.id'], name=op.f('fk_books_log_id_reading_logs')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('reading_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
